language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env: CFLAGS="-O0"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - if [[ $TRAVIS_PYTHON_VERSION < 3 ]]; then pip install -r requirements_py2.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION > 3 ]]; then pip install -r requirements_py3.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
script:
  python setup.py test
after_success:
  - coveralls

# See: http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false